defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .


input_paths:
  config_path_a: ./logs/synthetic_allign_depth/vine_C1_6/front/20220714_084853/config.yaml
  pointcloud_path_a: ./logs/synthetic_allign_depth/vine_C1_6/front/20220714_084853/pointclouds/10000.pcd
  model_path_a: ./logs/synthetic_allign_depth/vine_C1_6/front/20220714_084853/model/10000.pth

  config_path_b: './logs/synthetic_allign_depth/vine_C1_6/back/20220714_092632/config.yaml'
  pointcloud_path_b: ./logs/synthetic_allign_depth/vine_C1_6/back/20220714_092632/pointclouds/10000.pcd
  model_path_b: ./logs/synthetic_allign_depth/vine_C1_6/back/20220714_092632/model/10000.pth

  transform_init: "./data/pose_estimates/nerf/vine_C1_6/icp.npy"

output_paths:
  log: ./align/logs/icp3/vine_C1_6

n_rays: 4096
iters_per_epoch: 100
num_epochs: 20

renderer:
  z_bounds: [0.1, 1]
  steps_firstpass: [256]
  importance_steps: 128
  alpha: 0.2