
input_paths:
  logdir_a: ./logs/synthetic_allign_depth/vine_C1_7/front/20220714_100413
  model_a: "./logs/synthetic_allign_depth/vine_C1_7/front/20220714_100413/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign_depth/vine_C1_7/front/20220714_100413/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign_depth/vine_C1_7/back/20220714_104121
  model_b: "./logs/synthetic_allign_depth/vine_C1_7/back/20220714_104121/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign_depth/vine_C1_7/back/20220714_104121/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline_depth/vine_C1_7'