
input_paths:
  logdir_a: ./logs/synthetic_allign/vine_C2_3/front/20220711_072729
  model_a: "./logs/synthetic_allign/vine_C2_3/front/20220711_072729/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign/vine_C2_3/front/20220711_072729/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign/vine_C2_3/back/20220711_080411
  model_b: "./logs/synthetic_allign/vine_C2_3/back/20220711_080411/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign/vine_C2_3/back/20220711_080411/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline/vine_C2_3'