
input_paths:
  logdir_a: ./logs/synthetic_allign/vine_C1_1/front/20220710_165053
  model_a: "./logs/synthetic_allign/vine_C1_1/front/20220710_165053/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign/vine_C1_1/front/20220710_165053/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign/vine_C1_1/back/20220710_172703
  model_b: "./logs/synthetic_allign/vine_C1_1/back/20220710_172703/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign/vine_C1_1/back/20220710_172703/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline/vine_C1_1'