
input_paths:
  logdir_a: ./logs/synthetic_allign/vine_C2_0/front/20220711_023554
  model_a: "./logs/synthetic_allign/vine_C2_0/front/20220711_023554/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign/vine_C2_0/front/20220711_023554/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign/vine_C2_0/back/20220711_031215
  model_b: "./logs/synthetic_allign/vine_C2_0/back/20220711_031215/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign/vine_C2_0/back/20220711_031215/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline/vine_C2_0'