
input_paths:
  logdir_a: ./logs/synthetic_allign_depth/vine_C1_6/front/20220714_084853
  model_a: "./logs/synthetic_allign_depth/vine_C1_6/front/20220714_084853/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign_depth/vine_C1_6/front/20220714_084853/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign_depth/vine_C1_6/back/20220714_092632
  model_b: "./logs/synthetic_allign_depth/vine_C1_6/back/20220714_092632/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign_depth/vine_C1_6/back/20220714_092632/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline_depth/vine_C1_6'