
input_paths:
  logdir_a: ./logs/synthetic_allign_depth/vine_C1_4/front/20220714_061839
  model_a: "./logs/synthetic_allign_depth/vine_C1_4/front/20220714_061839/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign_depth/vine_C1_4/front/20220714_061839/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign_depth/vine_C1_4/back/20220714_065525
  model_b: "./logs/synthetic_allign_depth/vine_C1_4/back/20220714_065525/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign_depth/vine_C1_4/back/20220714_065525/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline_depth/vine_C1_4'