
input_paths:
  logdir_a: ./logs/synthetic_allign_depth/vine_C1_5/front/20220714_073242
  model_a: "./logs/synthetic_allign_depth/vine_C1_5/front/20220714_073242/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign_depth/vine_C1_5/front/20220714_073242/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign_depth/vine_C1_5/back/20220714_081041
  model_b: "./logs/synthetic_allign_depth/vine_C1_5/back/20220714_081041/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign_depth/vine_C1_5/back/20220714_081041/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline_depth/vine_C1_5'