
input_paths:
  logdir_a: ./logs/synthetic_allign_depth/vine_C1_1/front/20220714_011746
  model_a: "./logs/synthetic_allign_depth/vine_C1_1/front/20220714_011746/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign_depth/vine_C1_1/front/20220714_011746/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign_depth/vine_C1_1/back/20220714_015446
  model_b: "./logs/synthetic_allign_depth/vine_C1_1/back/20220714_015446/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign_depth/vine_C1_1/back/20220714_015446/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline_depth/vine_C1_1'