
input_paths:
  logdir_a: ./logs/synthetic_allign/vine_C1_7/front/20220711_012059
  model_a: "./logs/synthetic_allign/vine_C1_7/front/20220711_012059/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign/vine_C1_7/front/20220711_012059/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign/vine_C1_7/back/20220711_015847
  model_b: "./logs/synthetic_allign/vine_C1_7/back/20220711_015847/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign/vine_C1_7/back/20220711_015847/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline/vine_C1_7'