
input_paths:
  logdir_a: ./logs/synthetic_allign/vine_C1_4/front/20220710_214246
  model_a: "./logs/synthetic_allign/vine_C1_4/front/20220710_214246/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign/vine_C1_4/front/20220710_214246/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign/vine_C1_4/back/20220710_221916
  model_b: "./logs/synthetic_allign/vine_C1_4/back/20220710_221916/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign/vine_C1_4/back/20220710_221916/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline/vine_C1_4'