
input_paths:
  logdir_a: ./logs/synthetic_allign/vine_C2_5/front/20220711_095405
  model_a: "./logs/synthetic_allign/vine_C2_5/front/20220711_095405/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign/vine_C2_5/front/20220711_095405/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign/vine_C2_5/back/20220711_103106
  model_b: "./logs/synthetic_allign/vine_C2_5/back/20220711_103106/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign/vine_C2_5/back/20220711_103106/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline/vine_C2_5'