
input_paths:
  logdir_a: ./logs/synthetic_allign_depth/vine_C1_3/front/20220714_050321
  model_a: "./logs/synthetic_allign_depth/vine_C1_3/front/20220714_050321/model/10000.pth"
  pointcloud_a: "./logs/synthetic_allign_depth/vine_C1_3/front/20220714_050321/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/synthetic_allign_depth/vine_C1_3/back/20220714_054122
  model_b: "./logs/synthetic_allign_depth/vine_C1_3/back/20220714_054122/model/10000.pth"
  pointcloud_b: "./logs/synthetic_allign_depth/vine_C1_3/back/20220714_054122/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_pipeline_depth/vine_C1_3'