
input_paths:
  logdir_a: ./logs/full_allign_C8_6_2/20220701_115744
  model_a: "./logs/full_allign_C8_6_2/20220701_115744/model/10000.pth"
  pointcloud_a: "./logs/full_allign_C8_6_2/20220701_115744/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/full_allign_C8_6_2/20220701_123954
  model_b: "./logs/full_allign_C8_6_2/20220701_123954/model/10000.pth"
  pointcloud_b: "./logs/full_allign_C8_6_2/20220701_123954/pointclouds/pcd/10000.pcd"

log_dir: './allign/logs/full_allign/C8_6'

n_rays: 4096
iters_per_epoch: 100
num_epochs: 10

renderer:
  z_bounds: [0.1, 1]
  steps_firstpass: [512]

extract_geometry_values:
  mask_res: 128
  voxel_res: 512
  sigma_thresh: 100