
input_paths:
  root_dir: ./logs

  name_a: 'synthetic_allign_depth/vine_C1_0/front'
  run_dir_a: '20220714_000247'
  model_a: model/10000.pth
  pointcloud_a: pointclouds/pcd/10000.pcd
  
  name_b: 'synthetic_allign_depth/vine_C1_0/back'
  run_dir_b: '20220714_003959'
  model_b: model/10000.pth
  pointcloud_b: pointclouds/pcd/10000.pcd

n_rays: 4096
iters_per_epoch: 100
num_epochs: 20

renderer:
  z_bounds: [0.1, 1]
  steps_firstpass: [512]

extract_geometry_values:
  mask_res: 128
  voxel_res: 512
  sigma_thresh: 100