
input_paths:
  root_dir: ./logs/allign

  name_a: '0004'
  run_dir_a: '20220723_162216'
  model_a: model/3000.pth
  pointcloud_a: pointclouds/pcd/3000.pcd
  
  name_b: '0009'
  run_dir_b: '20220723_164644'
  model_b: model/3000.pth
  pointcloud_b: pointclouds/pcd/3000.pcd

n_rays: 4096
iters_per_epoch: 100
num_epochs: 20

renderer:
  z_bounds: [0.1, 1]
  steps_firstpass: [512]

extract_geometry_values:
  mask_res: 128
  voxel_res: 512
  sigma_thresh: 100