scene:
  scene_paths:
    - /home/casey/PhD/data/conan_scans/ROW_349_EAST_SLOW_0005/scene.json
    - /home/casey/PhD/data/conan_scans/ROW_349_WEST_SLOW_0008/scene.json
  frame_ranges:
    - null
    - null
  transforms:
    # - null
    - /home/casey/PhD/NeRF/allign/logs/real/0005_0008/20220719_202521/init_transform.npy
    - null
  
  image_scale: 0.25

  log:
    root_dir: './logs/real_data_bothsides'
  
inference:
  image:
    image_num: 303
    rotate: 270  # clockwise