
scene:
  scene_path: '/home/casey/Documents/PhD/data/synthetic_tree_assets/trees3/renders/vine_C2_1/back_close/cameras.json'
  image_scale: 0.5
  bound: 1.125
  remove_background_bool: False

log:
  root_dir: './logs/alpha'

trainer:
  num_epochs: 101
  iters_per_epoch: 100
  eval_freq: 20
  # n_rays: 4096
  n_rays: 8192

inference:
  n_rays: 4096
  image_num: 52
  voxel_res: 1024
  thresh: 10
  batch_size: 1_048_576

renderer:
  inner_near: 0.05
  inner_far: 1
  # inner_steps: 384
  inner_steps: 128
  outer_near: 1
  outer_far: 100
  # outer_steps: 192
  outer_steps: 64

nets:
  encoding:
    n_levels: 18
    n_features: 2
    log2_hashmap_size: 24
    precision: 'float32'
  
  encoding_dir:
    encoding: "SphericalHarmonics"
    degree: 4
    precision: 'float32'

  sigma:
    num_layers: 2
    hidden_dim: 64
    geo_feat_dim: 15

  color:
    num_layers: 3
    hidden_dim: 64
