
scene:
  # scene_path: /home/casey/Documents/PhD/data/conan_scans/ROW_349_EAST_SLOW_0006/scene.json
  scene_path: /home/casey/Documents/PhD/data/conan_scans/ROW_349_WEST_SLOW_0007/scene.json
  image_scale: 0.333
  inner_bound: 2
  outer_bound: 2.5
  real: True
  frame_range: null

log:
  root_dir: './logs/east_west_debug'
  eval_image_freq: 60
  eval_pointcloud_freq: 60
  save_weights_freq: 60

trainer:
  num_epochs: 60
  iters_per_epoch: 100
  n_rays: 16384
  dist_loss_lambda1: 1e-5
  dist_loss_lambda2: 1e-2

optimizer:
  encoding:
    lr: 2e-2
  latent_emb:
    lr: 2e-2
  net:
    weight_decay: 1e-6
    lr: 1e-3
  betas:
    - 0.9
    - 0.99
  eps: 1e-15

scheduler: step

inference:
  n_rays: 16384
  image_num: 52
  voxel_res: 1024
  thresh: 10
  batch_size: 2097152

renderer:
  steps:
    - 256
    - 128
    - 64
    - 32
  z_bounds:
    - 0.1
    - 1
    - 10
    - 100
    - 1000

  importance_steps: 128
  alpha: 0.2

nets:
  encoding:
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 24
    precision: float32
  
  encoding_dir:
    encoding: SphericalHarmonics
    degree: 4
    precision: float32

  latent_embedding:
    features: 48

  sigma:
    num_layers: 2
    hidden_dim: 64
    geo_feat_dim: 15

  color:
    num_layers: 3
    hidden_dim: 64