
input_paths:
  logdir_a: ./logs/full_allign/20220629_055751
  model_a: "./logs/full_allign/20220629_055751/model/3000.pth"
  pointcloud_a: "./logs/full_allign/20220629_055751/pointclouds/pcd/3000.pcd"

  logdir_b: ./logs/full_allign/20220629_061257
  model_b: "./logs/full_allign/20220629_061257/model/3000.pth"
  pointcloud_b: "./logs/full_allign/20220629_061257/pointclouds/pcd/3000.pcd"

log_dir: './allign/logs/tests/full_allign'

n_rays: 4096
iters_per_epoch: 100
num_epochs: 20

renderer:
  z_bounds: [0.1, 1]
  steps_firstpass: [512]

extract_geometry_values:
  mask_res: 128
  voxel_res: 512
  sigma_thresh: 100