
input_paths:
  logdir_a: ./logs/hashtable_outputs/vine_C1_0/front/20220710_153801
  model_a: "./logs/hashtable_outputs/vine_C1_0/front/20220710_153801/model/10000.pth"
  pointcloud_a: "./logs/hashtable_outputs/vine_C1_0/front/20220710_153801/pointclouds/pcd/10000.pcd"

  logdir_b: ./logs/hashtable_outputs/vine_C1_0/back/20220710_161406
  model_b: "./logs/hashtable_outputs/vine_C1_0/back/20220710_161406/model/10000.pth"
  pointcloud_b: "./logs/hashtable_outputs/vine_C1_0/back/20220710_161406/pointclouds/pcd/10000.pcd"

log_dir: './allign/real/0004_0009'

n_rays: 4096
iters_per_epoch: 100
num_epochs: 20

renderer:
  z_bounds: [0.1, 1]
  steps_firstpass: [512]

extract_geometry_values:
  mask_res: 128
  voxel_res: 512
  sigma_thresh: 100