python main.py ./configs/config_real.yaml ./configs/long/40.yaml
python main.py ./configs/config_real.yaml ./configs/long/60.yaml
python main.py ./configs/config_real.yaml ./configs/long/80.yaml
python main.py ./configs/config_real.yaml ./configs/long/100.yaml
python main.py ./configs/config_real.yaml ./configs/long/120.yaml
python main.py ./configs/config_real.yaml ./configs/long/140.yaml
python main.py ./configs/config_real.yaml ./configs/long/160.yaml
python main.py ./configs/config_real.yaml ./configs/long/180.yaml
python main.py ./configs/config_real.yaml ./configs/long/200.yaml
python main.py ./configs/config_real.yaml ./configs/long/220.yaml
python main.py ./configs/config_real.yaml ./configs/long/240.yaml
python main.py ./configs/config_real.yaml ./configs/long/260.yaml
python main.py ./configs/config_real.yaml ./configs/long/280.yaml
python main.py ./configs/config_real.yaml ./configs/long/300.yaml
python main.py ./configs/config_real.yaml ./configs/long/320.yaml
python main.py ./configs/config_real.yaml ./configs/long/340.yaml
python main.py ./configs/config_real.yaml ./configs/long/360.yaml
python main.py ./configs/config_real.yaml ./configs/long/380.yaml
python main.py ./configs/config_real.yaml ./configs/long/400.yaml
python main.py ./configs/config_real.yaml ./configs/long/420.yaml
python main.py ./configs/config_real.yaml ./configs/long/440.yaml
python main.py ./configs/config_real.yaml ./configs/long/460.yaml
python main.py ./configs/config_real.yaml ./configs/long/480.yaml
python main.py ./configs/config_real.yaml ./configs/long/500.yaml