scene:
  scene_paths:
  - /mnt/maara/genie_scans/blenheim_07_22/manual/05-07-22_10-17/368_east/scene.json
  frame_ranges:
  - null
  transforms:
  - null
  image_scale: 0.5
  inner_bound: 2
  outer_bound: 2.5
log:
  root_dir: ./genie_scans
  eval_image_freq: end
  eval_pointcloud_freq: end
  save_weights_freq: end
trainer:
  num_epochs: 30
  iters_per_epoch: 100
  n_rays: 16384
  dist_loss_lambda1: 1.0e-05
  dist_loss_lambda2: 0.01
  depth_loss_lambda1: 0
  depth_loss_lambda2: 0
optimizer:
  encoding:
    lr: 0.02
  latent_emb:
    lr: 0.02
  net:
    weight_decay: 1.0e-06
    lr: 0.001
  betas:
  - 0.9
  - 0.99
  eps: 1.0e-15
scheduler: step
inference:
  image:
    image_num: 303
    rotate: 270
  pointcloud:
    max_variance_npy: 0.1
    max_variance_pcd: 0.05
    distribution_area: 0.4
    sides_buffer: 3
    cams:
    - 1
    - 2
    - 3
    - 4
    freq: 20
renderer:
  steps:
  - 256
  - 128
  - 64
  - 32
  z_bounds:
  - 0.1
  - 1
  - 10
  - 100
  - 1000
  importance_steps: 128
  alpha: 0.2
nets:
  encoding:
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 24
    precision: float32
  encoding_dir:
    encoding: SphericalHarmonics
    degree: 4
    precision: float32
  latent_embedding:
    features: 48
  sigma:
    num_layers: 2
    hidden_dim: 64
    geo_feat_dim: 15
  color:
    num_layers: 3
    hidden_dim: 64
