defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .


input_paths:
  config_path_a: ./logs/synthetic_allign_depth/vine_C1_0/front/20220714_000247/config.yaml
  pointcloud_path_a: ./logs/synthetic_allign_depth/vine_C1_0/front/20220714_000247/pointclouds/10000.pcd
  model_path_a: ./logs/synthetic_allign_depth/vine_C1_0/front/20220714_000247/model/10000.pth

  config_path_b: './logs/synthetic_allign_depth/vine_C1_0/back/20220714_003959/config.yaml'
  pointcloud_path_b: ./logs/synthetic_allign_depth/vine_C1_0/back/20220714_003959/pointclouds/10000.pcd
  model_path_b: ./logs/synthetic_allign_depth/vine_C1_0/back/20220714_003959/model/10000.pth

n_rays: 4096
iters_per_epoch: 100
num_epochs: 20

renderer:
  z_bounds: [0.1, 1]
  steps_firstpass: [256]
  importance_steps: 128
  alpha: 0.2